model_list:
  - model_name: azure-gpt-4o
    litellm_params:
      model: azure/gpt-4o-2024-11-20 # Name defined in Azure Deployment
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      tpm: 3000000 # TPM of deployment is 30M
      rpm: 18000 # RPM of deployment is 180K

  - model_name: azure-gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini-2024-07-18 # Name defined in Azure Deployment
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      tpm: 5000000 # TPM of deployment is 50M
      rpm: 50000 # RPM of deployment is 500K

  - model_name: azure-o3-mini
    litellm_params:
      model: azure/o3-mini-2025-01-31 # Name defined in Azure Deployment
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: 2024-12-01-preview
      tpm: 5000000 # TPM of deployment is 50M
      rpm: 500 # RPM of deployment is 5K

  - model_name: azure-o1
    litellm_params:
      model: azure/o1-2024-12-17 # Name defined in Azure Deployment
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: 2024-12-01-preview
      tpm: 3000000 # TPM of deployment is 30M
      rpm: 500 # RPM of deployment is 5K

  - model_name: openai-gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY

  - model_name: openai-gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

general_settings:
  master_key: os.environ/BUTTERCUP_LITELLM_KEY
