[tool.black]
line-length = 80
target-version = ['py312']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools.packages]
find = {}

[project]
name = "orchestrator"
version = "0.1.0"
dependencies = [
    "uvicorn",
    "fastapi",
    "urllib3 >= 1.25.3, < 3.0.0",
    "python_dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]
requires-python = ">=3.12"

[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-xdist",
    "pytest-asyncio",
    "pytest-cov",
    "types-python-dateutil",
    "mypy",
    "tox",
    "flake8",
]
