apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-corpus-sync
  labels:
    app: {{ .Release.Name }}-corpus-sync
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-corpus-sync
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-corpus-sync
    spec:
      {{- include "buttercup.imagePullSecrets" . | nindent 6 }}
      containers:
      - name: corpus-sync
        image: "{{ .Values.global.fuzzerImage.repository }}:{{ .Values.global.fuzzerImage.tag }}"
        imagePullPolicy: {{ .Values.global.fuzzerImage.pullPolicy }}
        command: ["buttercup-corpus-sync",  "--redis-url", "{{ include "buttercup.core.redisUrl" . }}", "--wdir", "{{ include "buttercup.nodeLocalCrsScratchPath" . }}", "--log-level", "{{ include "buttercup.core.logLevel" . }}"]
        env:
        {{- include "buttercup.commonEnv" . | nindent 8 }}
        - name: BUTTERCUP_FUZZER_LOG_LEVEL
          value: {{ include "buttercup.core.logLevel" . }}
        volumeMounts:
        {{- include "buttercup.volumeMounts.scratch" . | nindent 8 }}
        {{- if .Values.global.volumes.nodeLocal.enabled }}
        - name: node-data
          mountPath: {{ .Values.global.volumes.nodeLocal.mountPath }}
        {{- end }}
      volumes:
      {{- include "buttercup.volumes.scratch" . | nindent 6 }}
      {{- if .Values.global.volumes.nodeLocal.enabled }}
      - name: node-data
        hostPath:
          path: {{ .Values.global.volumes.nodeLocal.hostPath }}
          type: DirectoryOrCreate
      {{- end }} 