{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fuzzer-bot
  labels:
    app: fuzzer-bot
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: fuzzer-bot
  template:
    metadata:
      labels:
        app: fuzzer-bot
    spec:
      {{- include "buttercup.imagePullSecrets" . | nindent 6 }}
      initContainers:
      {{- include "buttercup.waitForRedis" . | nindent 6 }}
      containers:
      - name: fuzzer-bot
        image: "{{ .Values.global.fuzzerImage.repository }}:{{ .Values.global.fuzzerImage.tag }}"
        imagePullPolicy: {{ .Values.global.fuzzerImage.pullPolicy }}
        command: ["buttercup-fuzzer", "--wdir", "/tmp", "--crs_scratch_dir", "{{ include "buttercup.nodeLocalCrsScratchPath" . }}", "--redis_url", "{{ include "buttercup.core.redisUrl" . }}", "--timer", "{{ .Values.timer }}", "--timeout", "{{ .Values.timeout }}", "--crash_dir_size_limit", "{{ include "buttercup.core.crashDirSizeLimit" . }}"]
        env: 
        {{- include "buttercup.env.nodeData" . | nindent 8 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        {{- include "buttercup.standardVolumeMounts" (dict "usesTasksStorage" false) | nindent 8 }}
        {{- include "buttercup.nodeLocalVolumeMount" . | nindent 8 }}
      volumes:
      {{- include "buttercup.volumes.scratch" . | nindent 6 }}
      {{- include "buttercup.nodeLocalVolume" . | nindent 6 }}
{{- end }}
