# Default values for competition-api chart
enabled: true
replicaCount: 1

service:
  port: 1323

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 4000m
    memory: 8Gi

dind:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 4000m
      memory: 8Gi

extraVolumeMounts:
  - name: tmp-storage
    mountPath: /tmp

nodeSelector: {}
tolerations: []
affinity: {}
