# Default values for competition-api chart
replicaCount: 1

service:
  type: NodePort
  port: 1323
  nodePort: 31323

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

dind:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 2Gi

extraVolumeMounts:
  - name: tmp-storage
    mountPath: /tmp

nodeSelector: {}
tolerations: []
affinity: {}
