# Default values for tracer-bot.
enabled: true

# Resource configurations
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

dind:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

# Number of replicas
replicaCount: 1

# Health check configuration
healthCheck:
  # Kubernetes probe configuration
  initialDelaySeconds: 60
  # Check every 5 minutes
  periodSeconds: 300
  timeoutSeconds: 10
  # Allow 2 failures (10 minutes total) before restarting
  failureThreshold: 2
