{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-competition-api
  labels:
    app: competition-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: competition-api
  template:
    metadata:
      labels:
        app: competition-api
    spec:
      {{- include "buttercup.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: competition-api
          image: "{{ .Values.global.competitionApiImage.repository }}:{{ .Values.global.competitionApiImage.tag }}"
          imagePullPolicy: {{ .Values.global.competitionApiImage.pullPolicy }}
          securityContext:
            privileged: true
          args: ["server"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- include "buttercup.dockerHostEnv" . | nindent 12 }}
            - name: SCANTRON_GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: ghcr
                  key: {{ if (lookup "v1" "Secret" .Release.Namespace "ghcr").data.scantron_github_pat }}scantron_github_pat{{ else }}pat{{ end }}
          volumeMounts:
            - name: scantron-config
              mountPath: /etc/scantron/scantron.yaml
              subPath: scantron.yaml
            {{- if .Values.extraVolumeMounts }}
            {{- range .Values.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- end }}
            {{- include "buttercup.nodeLocalVolumeMount" . | nindent 12 }}
        {{- include "buttercup.dindSidecar" . | nindent 8 }}
      volumes:
        {{- include "buttercup.dindVolume" . | nindent 8 }}
        {{- include "buttercup.volumes.scratch" . | nindent 8 }}

        - name: scantron-config
          configMap:
            name: {{ .Release.Name }}-scantron-config
        {{- if .Values.extraVolumeMounts }}
        {{- range .Values.extraVolumeMounts }}
        - name: {{ .name }}
          emptyDir: {}
        {{- end }}
        {{- end }}
        {{- include "buttercup.nodeLocalVolume" . | nindent 8 }}
{{- end }}
