{{/*
Define core system variables that are consistent across services
*/}}
{{- define "buttercup.core.redisUrl" -}}
redis://{{ .Release.Name }}-redis-master:6379
{{- end -}}

{{- define "buttercup.core.logLevel" -}}
{{- .Values.logLevel | default "debug" -}}
{{- end -}}

{{- define "buttercup.core.dockerEndpoint" -}}
tcp://localhost:2375
{{- end -}}


{{- define "buttercup.core.litellmEndpoint" -}}
http://{{ .Release.Name }}-litellm:4000
{{- end -}}

{{/*
Define common variables by categories
*/}}
{{- define "buttercup.env.dirs" }}
- name: CRS_SCRATCH_DIR
  value: {{ include "buttercup.dirs.crs_scratch" . }}
- name: TASKS_STORAGE_DIR
  value: {{ include "buttercup.dirs.tasks_storage" . }}
{{- end }}

{{- define "buttercup.env.redis" }}
- name: REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
{{- end }}

{{- define "buttercup.env.docker" }}
- name: DOCKER_HOST
  value: {{ include "buttercup.core.dockerEndpoint" . }}
{{- end }}

{{- define "buttercup.env.llm" }}
- name: BUTTERCUP_LITELLM_KEY
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-litellm-api-secrets
      key: BUTTERCUP_LITELLM_KEY
- name: BUTTERCUP_LITELLM_HOSTNAME
  value: {{ include "buttercup.core.litellmEndpoint" . }}
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: "{{ .Values.global.otel.endpoint }}"
- name: OTEL_EXPORTER_OTLP_HEADERS
  value: "Authorization=Basic {{ .Values.global.otel.token }}"
- name: OTEL_EXPORTER_OTLP_PROTOCOL
  value: "{{ .Values.global.otel.protocol | default "grpc" }}"
{{- end }}

{{- define "buttercup.env.timeouts" }}
- name: BUILD_TASK_TIMEOUT_MS
  value: "{{ int .Values.global.queueTimeouts.buildTaskTimeoutMs | default 120000 }}"
- name: BUILD_OUTPUT_TASK_TIMEOUT_MS
  value: "{{ int .Values.global.queueTimeouts.buildOutputTaskTimeoutMs | default 120000 }}"
- name: DOWNLOAD_TASK_TIMEOUT_MS
  value: "{{ int .Values.global.queueTimeouts.downloadTaskTimeoutMs | default 120000 }}"
- name: READY_TASK_TIMEOUT_MS
  value: "{{ int .Values.global.queueTimeouts.readyTaskTimeoutMs | default 120000 }}"
- name: DELETE_TASK_TIMEOUT_MS
  value: "{{ int .Values.global.queueTimeouts.deleteTaskTimeoutMs | default 120000 }}"
- name: CRASH_TASK_TIMEOUT_MS
  value: "{{ int .Values.global.queueTimeouts.crashTaskTimeoutMs | default 120000 }}"
- name: PATCH_TASK_TIMEOUT_MS
  value: "{{ int .Values.global.queueTimeouts.patchTaskTimeoutMs | default 120000 }}"
- name: CONFIRMED_VULNERABILITIES_TASK_TIMEOUT_MS
  value: "{{ int .Values.global.queueTimeouts.confirmedVulnerabilitiesTaskTimeoutMs | default 120000 }}"
- name: INDEX_TASK_TIMEOUT_MS
  value: "{{ int .Values.global.queueTimeouts.indexTaskTimeoutMs | default 120000 }}"
- name: INDEX_OUTPUT_TASK_TIMEOUT_MS
  value: "{{ int .Values.global.queueTimeouts.indexOutputTaskTimeoutMs | default 120000 }}"
- name: TRACED_VULNERABILITIES_TASK_TIMEOUT_MS
  value: "{{ int .Values.global.queueTimeouts.tracedVulnerabilitiesTaskTimeoutMs | default 120000 }}"
{{- end }}

{{/*
Define common environment for all services
*/}}
{{- define "buttercup.commonEnv" }}
{{- include "buttercup.env.llm" . | nindent 0 }}
{{- include "buttercup.env.timeouts" . | nindent 0 }}
{{- end }}

{{/*
Define Langfuse environment variables
*/}}
{{- define "buttercup.env.langfuse" }}
{{- if .Values.global.langfuse.enabled }}
{{- /* Set Langfuse environment variables from Kubernetes secret */ -}}
- name: LANGFUSE_HOST
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-langfuse-secrets
      key: LANGFUSE_HOST
- name: LANGFUSE_PUBLIC_KEY
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-langfuse-secrets
      key: LANGFUSE_PUBLIC_KEY
- name: LANGFUSE_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-langfuse-secrets
      key: LANGFUSE_SECRET_KEY
{{- end }}
{{- end }}


{{/*
Service-specific environment variables that utilize the standardized variables
*/}}
{{- define "buttercup.programModelEnv" }}
- name: BUTTERCUP_PROGRAM_MODEL_LOG_LEVEL
  value: {{ include "buttercup.core.logLevel" . }}
- name: BUTTERCUP_PROGRAM_MODEL_SERVE__REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
- name: BUTTERCUP_PROGRAM_MODEL_SERVE__SLEEP_TIME
  value: "5"
- name: BUTTERCUP_PROGRAM_MODEL_GRAPHDB_URL
  value: "ws://{{ .Release.Name }}-janusgraph:8182/gremlin"
- name: BUTTERCUP_PROGRAM_MODEL_SERVE__PYTHON
  value: "python"
- name: BUTTERCUP_PROGRAM_MODEL_SCRATCH_DIR
  value: {{ include "buttercup.dirs.crs_scratch" . }}q
- name: BUTTERCUP_PROGRAM_MODEL_GRAPHDB_ENABLED
  value: "false"
{{- end }}

{{- define "buttercup.downloaderEnv" }}
- name: BUTTERCUP_DOWNLOADER_LOG_LEVEL
  value: {{ include "buttercup.core.logLevel" . }}
- name: BUTTERCUP_DOWNLOADER_DOWNLOAD_DIR
  value: {{ include "buttercup.dirs.tasks_storage" . }}
- name: BUTTERCUP_DOWNLOADER_SERVE__SLEEP_TIME
  value: "5"
- name: BUTTERCUP_DOWNLOADER_SERVE__REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
{{- end }}

{{- define "buttercup.taskServerEnv" }}
- name: BUTTERCUP_TASK_SERVER_REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
- name: BUTTERCUP_TASK_SERVER_LOG_LEVEL
  value: {{ include "buttercup.core.logLevel" . }}
- name: BUTTERCUP_TASK_SERVER_HOST
  value: "0.0.0.0"
- name: BUTTERCUP_TASK_SERVER_PORT
  value: "{{ .Values.port | default 8000 }}"
- name: BUTTERCUP_TASK_SERVER_WORKERS
  value: "{{ .Values.workers | default 1 }}"
- name: BUTTERCUP_TASK_SERVER_COMPETITION_API_URL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-crs-config
      key: COMPETITION_API_URL
- name: BUTTERCUP_TASK_SERVER_COMPETITION_API_USERNAME
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-crs-config
      key: COMPETITION_API_KEY_ID
- name: BUTTERCUP_TASK_SERVER_COMPETITION_API_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-crs-config
      key: COMPETITION_API_KEY_TOKEN
- name: BUTTERCUP_TASK_SERVER_API_KEY_ID
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-crs-config
      key: CRS_API_KEY_ID
- name: BUTTERCUP_TASK_SERVER_API_TOKEN_HASH
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-crs-config
      key: CRS_API_KEY_TOKEN_HASH
{{- end }}

{{- define "buttercup.schedulerEnv" }}
- name: BUTTERCUP_SCHEDULER_LOG_LEVEL
  value: {{ include "buttercup.core.logLevel" . }}
- name: BUTTERCUP_SCHEDULER_TASKS_STORAGE_DIR
  value: {{ include "buttercup.dirs.tasks_storage" . }}
- name: BUTTERCUP_SCHEDULER_SCRATCH_DIR
  value: {{ include "buttercup.dirs.crs_scratch" . }}
- name: BUTTERCUP_SCHEDULER_SERVE__SLEEP_TIME
  value: "5"
- name: BUTTERCUP_SCHEDULER_SERVE__REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
- name: BUTTERCUP_SCHEDULER_SERVE__COMPETITION_API_URL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-crs-config
      key: COMPETITION_API_URL
- name: COMPETITION_API_KEY_ID
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-crs-config
      key: COMPETITION_API_KEY_ID
- name: COMPETITION_API_KEY_TOKEN
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-crs-config
      key: COMPETITION_API_KEY_TOKEN
{{- end }}

{{- define "buttercup.patcherEnv" }}
- name: BUTTERCUP_PATCHER_LOG_LEVEL
  value: {{ include "buttercup.core.logLevel" . }}
- name: BUTTERCUP_PATCHER_TASK_STORAGE_DIR
  value: {{ include "buttercup.dirs.crs_scratch" . }}
- name: BUTTERCUP_PATCHER_SCRATCH_DIR
  value: {{ include "buttercup.dirs.crs_scratch" . }}
- name: BUTTERCUP_PATCHER_SERVE__SLEEP_TIME
  value: "5"
- name: BUTTERCUP_PATCHER_SERVE__REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
- name: BUTTERCUP_PATCHER_DEV_MODE
  value: "false"
{{- end }}

{{- define "buttercup.buildBotEnv" }}
- name: BUTTERCUP_FUZZER_LOG_LEVEL
  value: {{ include "buttercup.core.logLevel" . }}
{{- end }}
