{{/*
Define core system variables that are consistent across services
*/}}
{{- define "buttercup.core.redisUrl" -}}
redis://{{ .Release.Name }}-redis-master:6379
{{- end -}}

{{- define "buttercup.core.logLevel" -}}
{{- .Values.logLevel | default "debug" -}}
{{- end -}}

{{- define "buttercup.core.dockerEndpoint" -}}
tcp://localhost:2375
{{- end -}}


{{- define "buttercup.core.litellmEndpoint" -}}
http://{{ .Release.Name }}-litellm:4000
{{- end -}}

{{/*
Define common variables by categories
*/}}
{{- define "buttercup.env.dirs" }}
- name: CRS_SCRATCH_DIR
  value: {{ include "buttercup.dirs.crs_scratch" . }}
- name: TASKS_STORAGE_DIR
  value: {{ include "buttercup.dirs.tasks_storage" . }}
{{- end }}

{{- define "buttercup.env.redis" }}
- name: REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
{{- end }}

{{- define "buttercup.env.docker" }}
- name: DOCKER_HOST
  value: {{ include "buttercup.core.dockerEndpoint" . }}
{{- end }}

{{- define "buttercup.env.llm" }}
- name: BUTTERCUP_LITELLM_KEY
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-litellm-api-secrets
      key: BUTTERCUP_LITELLM_KEY
- name: BUTTERCUP_LITELLM_HOSTNAME
  value: {{ include "buttercup.core.litellmEndpoint" . }}
{{- end }}

{{- define "buttercup.env.timeouts" }}
- name: BUILD_TASK_TIMEOUT_MS
  value: "120000" 
- name: BUILD_OUTPUT_TASK_TIMEOUT_MS
  value: "120000"
- name: DOWNLOAD_TASK_TIMEOUT_MS
  value: "120000"
- name: READY_TASK_TIMEOUT_MS
  value: "120000"
- name: DELETE_TASK_TIMEOUT_MS
  value: "120000"
- name: CRASH_TASK_TIMEOUT_MS
  value: "120000"
- name: PATCH_TASK_TIMEOUT_MS
  value: "120000"
- name: CONFIRMED_VULNERABILITIES_TASK_TIMEOUT_MS
  value: "120000"
- name: INDEX_TASK_TIMEOUT_MS
  value: "120000"
- name: INDEX_OUTPUT_TASK_TIMEOUT_MS
  value: "120000"
- name: TRACED_VULNERABILITIES_TASK_TIMEOUT_MS
  value: "120000"
{{- end }}

{{/*
Define common environment for all services
*/}}
{{- define "buttercup.commonEnv" }}
{{- include "buttercup.env.llm" . | nindent 0 }}
{{- include "buttercup.env.timeouts" . | nindent 0 }}
{{- end }}

{{/*
Define Langfuse environment variables
*/}}
{{- define "buttercup.env.langfuse" }}
{{- if .Values.global.langfuse.enabled }}
{{- /* Set Langfuse environment variables from Kubernetes secret */ -}}
- name: LANGFUSE_HOST
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-langfuse-secrets
      key: LANGFUSE_HOST
- name: LANGFUSE_PUBLIC_KEY
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-langfuse-secrets
      key: LANGFUSE_PUBLIC_KEY
- name: LANGFUSE_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-langfuse-secrets
      key: LANGFUSE_SECRET_KEY
{{- end }}
{{- end }}


{{/*
Service-specific environment variables that utilize the standardized variables
*/}}
{{- define "buttercup.programModelEnv" }}
- name: BUTTERCUP_PROGRAM_MODEL_LOG_LEVEL
  value: {{ include "buttercup.core.logLevel" . }}
- name: BUTTERCUP_PROGRAM_MODEL_SERVE__REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
- name: BUTTERCUP_PROGRAM_MODEL_SERVE__SLEEP_TIME
  value: "5"
- name: BUTTERCUP_PROGRAM_MODEL_SERVE__WDIR
  value: {{ include "buttercup.dirs.crs_scratch" . }}
- name: BUTTERCUP_PROGRAM_MODEL_GRAPHDB_URL
  value: "ws://{{ .Release.Name }}-janusgraph:8182/gremlin"
- name: BUTTERCUP_PROGRAM_MODEL_SERVE__PYTHON
  value: "python"
{{- end }}

{{- define "buttercup.downloaderEnv" }}
- name: BUTTERCUP_DOWNLOADER_LOG_LEVEL
  value: {{ include "buttercup.core.logLevel" . }}
- name: BUTTERCUP_DOWNLOADER_DOWNLOAD_DIR
  value: {{ include "buttercup.dirs.tasks_storage" . }}
- name: BUTTERCUP_DOWNLOADER_SERVE__SLEEP_TIME
  value: "5"
- name: BUTTERCUP_DOWNLOADER_SERVE__REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
{{- end }}

{{- define "buttercup.taskServerEnv" }}
- name: BUTTERCUP_TASK_SERVER_REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
- name: BUTTERCUP_TASK_SERVER_LOG_LEVEL
  value: {{ include "buttercup.core.logLevel" . }}
- name: BUTTERCUP_TASK_SERVER_HOST
  value: "0.0.0.0"
- name: BUTTERCUP_TASK_SERVER_PORT
  value: "8000"
- name: BUTTERCUP_TASK_SERVER_WORKERS
  value: "1"
- name: BUTTERCUP_TASK_SERVER_API_KEY_ID
  value: "515cc8a0-3019-4c9f-8c1c-72d0b54ae561"
- name: BUTTERCUP_TASK_SERVER_API_TOKEN_HASH
  value: '$argon2id$v=19$m=65536,t=3,p=4$Dg1v6NPGTyXPoOPF4ozD5A$wa/85ttk17bBsIASSwdR/uGz5UKN/bZuu4wu+JIy1iA'
{{- end }}

{{- define "buttercup.schedulerEnv" }}
- name: BUTTERCUP_SCHEDULER_LOG_LEVEL
  value: {{ include "buttercup.core.logLevel" . }}
- name: BUTTERCUP_SCHEDULER_TASKS_STORAGE_DIR
  value: {{ include "buttercup.dirs.tasks_storage" . }}
- name: BUTTERCUP_SCHEDULER_SCRATCH_DIR
  value: {{ include "buttercup.dirs.crs_scratch" . }}
- name: BUTTERCUP_SCHEDULER_SERVE__SLEEP_TIME
  value: "5"
- name: BUTTERCUP_SCHEDULER_SERVE__REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
- name: BUTTERCUP_SCHEDULER_SERVE__COMPETITION_API_URL
  value: "http://{{ .Release.Name }}-competition-api:{{ .Values.competitionApi.port | default 1323 }}"
{{- end }}

{{- define "buttercup.patcherEnv" }}
- name: BUTTERCUP_PATCHER_LOG_LEVEL
  value: {{ include "buttercup.core.logLevel" . }}
- name: BUTTERCUP_PATCHER_TASK_STORAGE_DIR
  value: {{ include "buttercup.dirs.crs_scratch" . }}
- name: BUTTERCUP_PATCHER_SCRATCH_DIR
  value: {{ include "buttercup.dirs.crs_scratch" . }}
- name: BUTTERCUP_PATCHER_SERVE__SLEEP_TIME
  value: "5"
- name: BUTTERCUP_PATCHER_SERVE__REDIS_URL
  value: {{ include "buttercup.core.redisUrl" . }}
- name: BUTTERCUP_PATCHER_DEV_MODE
  value: "false"
{{- end }}
